Feature/1.7.x merge master (#214)
*  v1.6.12 - New repoter support http server and elasticsearch (#167)

*  new repoter support http server and elasticsearch

* print more info when load script failed

* bugfix

* remove unused import

* fix :repoter crash if not set reporter.workspace (#170)

* v1.6.14 - Feature/notification center time (#171)

* add date and month in notification center message

* fix bug - checker register duplicate functions to event bus (#181)

* fix bug

* rm built-in object

* v1.6.16 - Fix bug (#188)

AttributeError: 'CheckerEventHandler' object has no attribute 'publish'
AttributeError: 'CheckerEventHandler' object has no attribute 'listeners'

* feature/report-eventbus (#196)

* support report all eventbus message into reporter;reopen channel flow.request

* update unit tests

* Bump lodash.defaultsdeep from 4.6.0 to 4.6.1 in /frontend (#180)

Bumps [lodash.defaultsdeep](https://github.com/lodash/lodash) from 4.6.0 to 4.6.1.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.6.0...4.6.1)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump lodash from 4.17.11 to 4.17.14 in /frontend (#183)

Bumps [lodash](https://github.com/lodash/lodash) from 4.17.11 to 4.17.14.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.17.11...4.17.14)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump lodash from 4.17.11 to 4.17.15 in /frontend (#206)

Bumps [lodash](https://github.com/lodash/lodash) from 4.17.11 to 4.17.15.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.17.11...4.17.15)

Signed-off-by: dependabot[bot] <support@github.com>

* load background task of plugin manifast (#208)