Feature/merge master 1.6.17 (#197)
*  v1.6.12 - New repoter support http server and elasticsearch (#167)

*  new repoter support http server and elasticsearch

* print more info when load script failed

* bugfix

* remove unused import

* fix :repoter crash if not set reporter.workspace (#170)

* v1.6.14 - Feature/notification center time (#171)

* add date and month in notification center message

* fix bug - checker register duplicate functions to event bus (#181)

* fix bug

* rm built-in object

* v1.6.16 - Fix bug (#188)

AttributeError: 'CheckerEventHandler' object has no attribute 'publish'
AttributeError: 'CheckerEventHandler' object has no attribute 'listeners'

* feature/report-eventbus (#196)

* support report all eventbus message into reporter;reopen channel flow.request

* update unit tests