v1.7.0 (#224)
* Mock data manager update & add new api for data management (#169)

* data manager

* new data manager

* mock handler

* update mock rules conflict checker

* add unit test

* Add cut\copy\paste api

* update main.vue

* fix: mock server crash if there is no data root path in config

* Update mock rule conflict checker (#172)

* data manager

* new data manager

* mock handler

* update mock rules conflict checker

* add unit test

* Add cut\copy\paste api

* update main.vue

* fix: mock server crash if there is no data root path in config

* update conflict checker

* Feature/datamanager frontend (#173)

add frontend of datamanager documents tree

* Feature/datamanager frontend (#174)

* add notice of conflict check

* solve conflict

* update api response interceptor (#175)

* update api response interceptor

* fix axios response handler error

* dm delete tooooo slow (#176)

* update api response interceptor

* fix axios response handler error

* fix dm delete data slow

* New mock group selector (#177)

* update api response interceptor

* fix axios response handler error

* fix dm delete data slow

* Update inspector: Add new mock data group select window

* fix api error

* fix button bar method name

* Update mock data selector (#178)

* update api response interceptor

* fix axios response handler error

* fix dm delete data slow

* Update inspector: Add new mock data group select window

* fix api error

* fix button bar method name

* update mock data selector UE

* support delete group and delete data (#179)

* organize dataManager store (#182)

* optimize store

* remove debug code

* Bugfix/delete data error (#184)

* solve delete data error

* Feature/create group and data (#186)

* create group and data

* update code

* update code

* fix detail

* fix codacy issue

* Feature/change tree toggle icon (#185)

* change tree toggle icon

* update code

* remove unused code

* update code

* Feature/inspector save to new data manager (#187)

* Inspector button update

* save flow to activated group

* new data detail

* update api;fix save HTTP data error;new DataDetail page

* mock data editor

* fix add data error

* update api

* "->'

* Feature/update conflict text (#189)

* update conflict display and text

* update code

* support copy and paste group and data (#190)

* fix: new plugin index page view function error (#191)

* Bugfix/datamanager copy not work (#192)

* fix: new plugin index page view function error

* fix data-manager bug. update inspector-mock-group-selector

* refector logger and bugfix (#193)

* merge from master (#194)

*  v1.6.12 - New repoter support http server and elasticsearch (#167)

*  new repoter support http server and elasticsearch

* print more info when load script failed

* bugfix

* remove unused import

* fix :repoter crash if not set reporter.workspace (#170)

* v1.6.14 - Feature/notification center time (#171)

* add date and month in notification center message

* fix bug - checker register duplicate functions to event bus (#181)

* fix bug

* rm built-in object

* v1.6.16 - Fix bug (#188)

AttributeError: 'CheckerEventHandler' object has no attribute 'publish'
AttributeError: 'CheckerEventHandler' object has no attribute 'listeners'

* rm console logo green BG (#195)

* Feature/merge master 1.6.17 (#197)

*  v1.6.12 - New repoter support http server and elasticsearch (#167)

*  new repoter support http server and elasticsearch

* print more info when load script failed

* bugfix

* remove unused import

* fix :repoter crash if not set reporter.workspace (#170)

* v1.6.14 - Feature/notification center time (#171)

* add date and month in notification center message

* fix bug - checker register duplicate functions to event bus (#181)

* fix bug

* rm built-in object

* v1.6.16 - Fix bug (#188)

AttributeError: 'CheckerEventHandler' object has no attribute 'publish'
AttributeError: 'CheckerEventHandler' object has no attribute 'listeners'

* feature/report-eventbus (#196)

* support report all eventbus message into reporter;reopen channel flow.request

* update unit tests

* Fix:cannot-create-new-data (#198)

* Fix:cannot-create-new-data;raise exception list.remove(x) x not in list when delete new node

* update unit test

* feature/frontend-error-message (#199)

* add error message in frontend

* fix codacy issue

* disable draggable; update unshownInfoKey of group properties (#200)

* Feature/edit group properties (#202)

* support several actions on group detail: edit, add and delete

* change state of isGroupDetailChanged

* keep conflict loading state in store

* upgrade delete button

* remove save button state in group detail

* fix undeletable key could be deleted error

* solve save mock data error (#204)

* bugfix (#207)

* fix bug (#209)

* change editable state of secondary_search_id (#212)

* sort mock data & can activate in data manager & fix data tree style (#213)

* sort mock data & can activate in data manager & fix data tree style

* Activated group name str add space

* Feature/1.7.x merge master (#214)

*  v1.6.12 - New repoter support http server and elasticsearch (#167)

*  new repoter support http server and elasticsearch

* print more info when load script failed

* bugfix

* remove unused import

* fix :repoter crash if not set reporter.workspace (#170)

* v1.6.14 - Feature/notification center time (#171)

* add date and month in notification center message

* fix bug - checker register duplicate functions to event bus (#181)

* fix bug

* rm built-in object

* v1.6.16 - Fix bug (#188)

AttributeError: 'CheckerEventHandler' object has no attribute 'publish'
AttributeError: 'CheckerEventHandler' object has no attribute 'listeners'

* feature/report-eventbus (#196)

* support report all eventbus message into reporter;reopen channel flow.request

* update unit tests

* Bump lodash.defaultsdeep from 4.6.0 to 4.6.1 in /frontend (#180)

Bumps [lodash.defaultsdeep](https://github.com/lodash/lodash) from 4.6.0 to 4.6.1.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.6.0...4.6.1)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump lodash from 4.17.11 to 4.17.14 in /frontend (#183)

Bumps [lodash](https://github.com/lodash/lodash) from 4.17.11 to 4.17.14.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.17.11...4.17.14)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump lodash from 4.17.11 to 4.17.15 in /frontend (#206)

Bumps [lodash](https://github.com/lodash/lodash) from 4.17.11 to 4.17.15.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.17.11...4.17.15)

Signed-off-by: dependabot[bot] <support@github.com>

* load background task of plugin manifast (#208)

* remove mock data item activate button (#215)

*  v1.6.12 - New repoter support http server and elasticsearch (#167)

*  new repoter support http server and elasticsearch

* print more info when load script failed

* bugfix

* remove unused import

* fix :repoter crash if not set reporter.workspace (#170)

* v1.6.14 - Feature/notification center time (#171)

* add date and month in notification center message

* fix bug - checker register duplicate functions to event bus (#181)

* fix bug

* rm built-in object

* v1.6.16 - Fix bug (#188)

AttributeError: 'CheckerEventHandler' object has no attribute 'publish'
AttributeError: 'CheckerEventHandler' object has no attribute 'listeners'

* feature/report-eventbus (#196)

* support report all eventbus message into reporter;reopen channel flow.request

* update unit tests

* Bump lodash.defaultsdeep from 4.6.0 to 4.6.1 in /frontend (#180)

Bumps [lodash.defaultsdeep](https://github.com/lodash/lodash) from 4.6.0 to 4.6.1.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.6.0...4.6.1)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump lodash from 4.17.11 to 4.17.14 in /frontend (#183)

Bumps [lodash](https://github.com/lodash/lodash) from 4.17.11 to 4.17.14.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.17.11...4.17.14)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump lodash from 4.17.11 to 4.17.15 in /frontend (#206)

Bumps [lodash](https://github.com/lodash/lodash) from 4.17.11 to 4.17.15.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.17.11...4.17.15)

Signed-off-by: dependabot[bot] <support@github.com>

* load background task of plugin manifast (#208)

* remove mock data activate button

* update dependencies & add sonarcloud (#216)

* update dependencies & add sonarcloud

* update sonar config

* rm sonar addon

* update travis config

* Bug fix (#218)

* feature/adjust-group-info-display (#219)

* adjust group info display; fix bug

* update unit test

* prop file add newline for each node (#221)

* feature/datamanager-support-search-id (#222)

* support search group id; ignore case of search_str

* update code

* Mock data auto update to v1.7.0 (#223)

* Mock data auto update to v1.7.0

* Update log text

* reporter.py

* fix mock data update tools log

* fix codacy issues

* rm unused import